Repository hmcts/ccd-case-migration-starter, pull requests merged in 2023-05, with the labels that each got.

#77 CCD-4607 : Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-migration-pr-77

#74 CCD-4598 Update renovate
  .github/renovate.json
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-migration-pr-74

#71 Add suppressCves task
  .github/workflows/ci.yml
  .github/workflows/dependency-check.yml
  build.gradle
  config/owasp/suppressions.xml
  gradle/suppress.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-migration-pr-71

#97 CCD-4607 : Fix for CVE-2023-20862
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-migration-pr-97

#119 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-migration-pr-119
