Repository hmcts/ccd-case-migration-starter, pull requests merged in 2024-08, with the labels that each got.

#150 enable fortify failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-migration-pr-150

#151 CCD-5159:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-migration-pr-151

#152 Revert "CCD-5159:"
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-migration-pr-152
